USE dev;

CREATE TABLE IF NOT EXISTS messages (
  id CHAR(36) PRIMARY KEY DEFAULT (BIN_TO_UUID(UUID_TO_BIN(UUID(), 1))),
  text                   VARCHAR(1000)      NOT NULL
) ENGINE=InnoDB DEFAULT CHARACTER SET=utf8mb4;