/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package sample.app

import io.ktor.server.application.*
import sample.app.plugins.*

fun main(args: Array<String>): Unit = io.ktor.server.netty.EngineMain.main(args)

fun Application.module() {
    configureRouting()
    configureSerialization()
}